version: '3.1'

services:

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_USER=app
      - POSTGRES_DATABASE=app
      - POSTGRES_PASSWORD=12345